version: '3'
services:
  ferrytale:
    build: .
    image: ferrytale
    ports:
          - "33333:33333"
    links:
      - database

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=ferrytale"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "33306:3306"
volumes:
  dbdata: