version: '2'
services:
#  app:
#    build:
#      context: ./
#      dockerfile: Dockerfile.app
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=ferrytale"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "33062:3306"
volumes:
  dbdata: